[build]
  command = "./build.sh"
  publish = "build"  # Frontend build

# API routing
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

# WebSocket routing
[[redirects]]
  from = "/bids/*"
  to = "/.netlify/functions/server/bids/:splat"
  status = 200

# Client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
