[build]
  command = "./build.sh"
  publish = "backend"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = ["!404", "!403"]}

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/bids/*"
  to = "/.netlify/functions/server/bids/:splat"
  status = 200
  force = true
